### PR TITLE
Bugfix for #175

### PR DESCRIPTION
**Pull request by DairyProducts**
I don't know if this fix works, I'm opening a PR so I can get the mobile link for a deploy preview. I'll close the PR if it doesn't work out.

### CODE REVIEW

**Comment by DairyProducts** [comment]
Doesn't seem to have worked, the iOS arrow emoji is still showing. Removing the superscript makes the arrow bigger though.

**Comment by trevorshannon** [comment]
Netlify will automatically create a "branch deploy" for each brach created.  When you make a branch and publish it to Github, a build is kicked off and the site will be available at {branch_name}--ueo.netlify.app

This branch has a deploy at https://link-arrow-fix--ueo.netlify.app/

Any time you push new commits to the branch, Netlify will rebuild the site for you.  

You can also access a local development server without the need to even make a branch or commit by using the `--live` option of `netlify dev`.  See the [documentation](https://docs.netlify.com/cli/local-development/#share-a-live-development-server) for details.

Perhaps this can be in the README as a helpful tip.

**Comment by DairyProducts** [comment]
> This branch has a deploy at https://link-arrow-fix--ueo.netlify.app/

How does this work with branches in slashes in their name, considering the slashes are (probably) not allowed in URLs?

**Comment by trevorshannon** [comment]
Good question.  It replaces the slash with a hyphen.  Unfortunately I could not find it in the [documentation](https://docs.netlify.com/site-deploys/overview/#definitions) anywhere, but was able to verify via my Netlify account and one of your branches: https://eligibility-fss--ueo.netlify.app/

**Comment by trevorshannon** [comment]
Oop, I missed your comment edit!  I'm glad you got it figured out.

**Pull request closed without merging**
